repos:
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
     - id: nbqa-black
     - id: nbqa-pyupgrade
       additional_dependencies: [pyupgrade==2.7.3]
     - id: nbqa-isort
       additional_dependencies: [isort==5.6.4]
