[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "matplotlib>=3.10.1",
    "pre-commit>=4.2.0",
    "tensorboard>=2.18.0",
    "tensorflow==2.18",
]
